### ISSUE TITLE
RuntimeError: cuDNN

### ISSUE THREAD

**Issue by Limbicnation** [neuralchen/ASMAGAN#6]
Hi I get the following error when running the code:

`RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED when calling backward()`

I would appreciate your help on how to resolve this. 

Thank you!

Gero

**Comment by NNNNAI** [comment]
Sorry for the late respond ,did you follow the installation section in readme.md to build your environment? And what kind of GPU did you use.

**Comment by Limbicnation** [comment]
Hi there. No worries!
I did try to follow the installation instructions. However, I did get an error when building the environment with python 3.6.
I am using an RTX 3090 card.

PS: I am not in office at the moment, but I will try the installation instructions again in January.

Thanks for the reply!

**Comment by NNNNAI** [comment]
Oh, I suggest you to use CUDA >=11.1,because the defualt cuda in the installation instructions is 10.1 which is not suitable for 30 serial GPU

**Comment by Limbicnation** [comment]
Thanks for the information, I will try that!

**Comment by Limbicnation** [comment]
Hello,

I am still getting an error:

`raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled`

Also I have installed CUDA 11.5

`| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5   `

I appreciate your help. Thanks!

regards,
Gero

**Comment by Limbicnation** [comment]
When I follow these instructions:

`conda create -n ASMA python=3.7
conda activate ASMA
conda install pytorch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1 cudatoolkit=11.3 -c pytorch -c conda-forge
pip install pyyaml paramiko pandas requests tensorboard tensorboardX tqdm`

I get the following error:

`anaconda3/envs/ASMA/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 45, in _interpolation_modes_from_int
    return inverse_modes_mapping[i]
KeyError: 1920
`

**Comment by birolkuyumcu** [comment]
for KeyError @Limbicnation 

open "ASMAGAN/data_tools/test_data_loader_resize.py" 
at line 36 correct like this
`transform.append(T.Resize((1088,1920)))`

**Comment by Limbicnation** [comment]
@birolkuyumcu Thank you very much!
This works perfectly now!
:+1:
